### ISSUE TITLE
Is it possible sync with Firestore?

### ISSUE THREAD

**Issue by cyrsis** [felangel/hydrated_bloc#1]
I have to write lot of CRUD lately.

It maybe a  much better approach then using CRUD event in the Flutter Bloc

Then all I have to do is keep track of the uid, I think

Please advice.

**Comment by felangel** [comment]
Hi @cyrsis 👋 
Thanks for opening an issue!

You can definitely hook it up to Firestore. All you need to do is write your own HydratedBlocFirestoreStorage class which implements HydatedBlocStorage and use it instead of the shared preferences storage. 

Let me know if that makes sense or if you have additional questions. 👍

**Comment by cyrsis** [comment]
I think I am good, Thanks

somehow I ran into out of sync but I choose local state as true state save me a lot hours.
