### ISSUE TITLE
Question: Scoping bloc persistence by ID 

### ISSUE THREAD

**Issue by KieranLafferty** [felangel/hydrated_bloc#2]
First, thank you for creating such an easy to use framework for creating and persisting blocs!

I've implemented a hydrated bloc which I want to restore bloc state based on a unique ID that is contextually relevant to the bloc. As an example, imagine a user profile page on Facebook. If I were to use the bloc persistence for a users profile, then go to another users profile it would restore the first user's profile for me since the persisted bloc wasn't scoped by ID for the user.

To get around this I made my `LoadedState` work with `JsonSerializable()` then implemented the following toJson/fromJson in my bloc

```
  @override
  StoryEpisodesState fromJson(Map<String, dynamic> json) {
    if (json['story_id'] == this.repository.client.storyID) {
      return StoryEpisodesStateLoaded.fromJson(json['state']);
    }
  }

  @override
  Map<String, dynamic> toJson(StoryEpisodesState state) {
    if (state is StoryEpisodesStateLoaded) {
      return {
        'story_id': this.repository.client.storyID,
        'state': state.toJson(),
      };
    }
  }
```

The problem with the above is that it is only storing one JSON at a time which means it will only persist the most recently visited story and all stories visited before that load from scratch again.

Is there a better way to accomplish this such that each page that I visit will be cached and stored for future use allowing me to store bloc states for as many pages as I want? 

best,

Kieran

**Comment by felangel** [comment]
Hi @KieranLafferty 👋 
Thanks for opening an issue and for the positive feedback!

Unfortunately, the functionality you're asking for is not within the scope of `hydrated_bloc` because `hydrated_bloc` only stores the last state of each bloc. If you want to cache all of the various data per storyID, I'd recommend creating a cache and using it within your repository layer. You can checkout the [Github Search](https://felangel.github.io/bloc/#/flutterangulargithubsearch?id=github-cache) tutorial for an example.

Hope that helps! 👍
