### ISSUE TITLE
Data loss when upgrading from v3.1.0 to latest version

### ISSUE THREAD

**Issue by orsenkucher** [felangel/hydrated_bloc#66]
**Describe the bug**
I believe transition from `v3.1.0` to `v5.0.1` should be as safe as from `v3.1.0` to `v4.1.1`

**To Reproduce**
- Upgrade project from v3 to v5

**Expected behavior**
a) No data loss
b) This behavior is very explicitly stated in changelog and readme

**Comment by felangel** [comment]
Hey @orsenkucher 👋
Thanks for opening an issue!

I decided to do this intentionally because you can downgrade to 4.1.1 first then upgrade to 5.x.x and you should have your data. I really wanted to remove the migration code given the cubit refactor so sorry for any inconvenience but hopefully it’s a quick fix and the number of impacted developers is minimal 🤞

**Comment by orsenkucher** [comment]
Break-test passes now🥳
Thanks! @felangel
